CREATE TABLE shop (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_name TEXT NOT NULL,
  item_desc TEXT,
  price NUMERIC NOT NULL,
  date_harvested DATE,
  img_url TEXT,
  cat_id INTEGER REFERENCES shop_categories(id) NOT NULL
);